version: "3.9"

services:
  api:
    build: .
    restart: always
    container_name: api
    hostname: api
    ports:
      - 3000:3000
    networks:
      - backend
    links:
      - "db-test:db-mongo"
    volumes:
      - .:/usr/app
    depends_on:
      - db-test
    #cpu_shares: 2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 64M
  
  db-test:
    image: mongo
    restart: always
    hostname: db-test
    networks:
      - backend
    expose:
      - 27017
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

volumes:
  db-data:

networks:
  backend: {}